
program driver
  use crmdims
  use params, only: crm_rknd, crm_iknd, crm_lknd, r8
  use crm_input_module
  use crm_output_module
  use crm_state_module
  use crm_rad_module
  use dmdf
  use crm_module
  implicit none
  type(crm_input_type)         :: crm_input
  type(crm_output_type)        :: crm_output
  type(crm_state_type)         :: crm_state
  type(crm_rad_type)           :: crm_rad
  integer          , parameter :: plev   = PLEV
  character(len=64), parameter :: prefix = INPUT_FILE
  real(crm_rknd), allocatable  :: lat0  (:)
  real(crm_rknd), allocatable  :: long0 (:)
  real(crm_rknd), allocatable  :: dt_gl (:)
  integer                      :: ncrms, icrm
  real(crm_rknd), allocatable :: read_crm_input_zmid       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_zint       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_tl         (:,:)
  real(crm_rknd), allocatable :: read_crm_input_ql         (:,:)
  real(crm_rknd), allocatable :: read_crm_input_qccl       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_qiil       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_pmid       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_pint       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_pdel       (:,:)
  real(crm_rknd), allocatable :: read_crm_input_ul         (:,:)
  real(crm_rknd), allocatable :: read_crm_input_vl         (:,:)
  real(crm_rknd), allocatable :: read_crm_state_u_wind     (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_v_wind     (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_w_wind     (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_temperature(:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_qt         (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_qp         (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_state_qn         (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_qrad         (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_temperature  (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_qv           (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_qc           (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_qi           (:,:,:,:)
  real(crm_rknd), allocatable :: read_crm_rad_cld          (:,:,:,:)

  call dmdf_num_records(prefix,ncrms)
  write(*,*) "File   : ", trim(prefix)
  write(*,*) "Samples: ", ncrms
  write(*,*) "crm_nx : ", crm_nx
  write(*,*) "crm_ny : ", crm_ny
  write(*,*) "crm_dx : ", crm_dx
  write(*,*) "crm_dt : ", crm_dt
  write(*,*) "plev   : ", plev 

  ! Allocate model data
  call crm_input%initialize (           ncrms,plev)
  call crm_output_initialize(crm_output,ncrms,plev)
  ! These are normally allocated by pbuf, so we have to do it explicitly
  allocate( crm_state%u_wind     (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%v_wind     (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%w_wind     (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%temperature(ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%qt         (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%qp         (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_state%qn         (ncrms,crm_nx,crm_ny,crm_nz) )
  allocate( crm_rad%qrad         (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( crm_rad%temperature  (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( crm_rad%qv           (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( crm_rad%qc           (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( crm_rad%qi           (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( crm_rad%cld          (ncrms,crm_nx_rad,crm_ny_rad,crm_nz) )
  allocate( lat0                 (ncrms) )
  allocate( long0                (ncrms) )
  allocate( dt_gl                (ncrms) )
  
  ! Allocate transposed arrays because this is the storage format in netcdf
  allocate( read_crm_input_zmid       (plev  ,ncrms))
  allocate( read_crm_input_zint       (plev+1,ncrms))
  allocate( read_crm_input_tl         (plev  ,ncrms))
  allocate( read_crm_input_ql         (plev  ,ncrms))
  allocate( read_crm_input_qccl       (plev  ,ncrms))
  allocate( read_crm_input_qiil       (plev  ,ncrms))
  allocate( read_crm_input_pmid       (plev  ,ncrms))
  allocate( read_crm_input_pint       (plev+1,ncrms))
  allocate( read_crm_input_pdel       (plev  ,ncrms))
  allocate( read_crm_input_ul         (plev  ,ncrms))
  allocate( read_crm_input_vl         (plev  ,ncrms))
  allocate( read_crm_state_u_wind     (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_v_wind     (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_w_wind     (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_temperature(crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_qt         (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_qp         (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_state_qn         (crm_nx    ,crm_ny    ,crm_nz,ncrms) )
  allocate( read_crm_rad_qrad         (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )
  allocate( read_crm_rad_temperature  (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )
  allocate( read_crm_rad_qv           (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )
  allocate( read_crm_rad_qc           (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )
  allocate( read_crm_rad_qi           (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )
  allocate( read_crm_rad_cld          (crm_nx_rad,crm_ny_rad,crm_nz,ncrms) )

  ! Read in the samples to drive the code
  call dmdf_read( dt_gl                      , prefix , trim("dt_gl            ") , 1 , ncrms , .true.  , .false. )
  call dmdf_read( lat0                       , prefix , trim("latitude0        ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( long0                      , prefix , trim("longitude0       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_zmid        , prefix , trim("in_zmid          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_zint        , prefix , trim("in_zint          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_tl          , prefix , trim("in_tl            ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_ql          , prefix , trim("in_ql            ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_qccl        , prefix , trim("in_qccl          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_qiil        , prefix , trim("in_qiil          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_pmid        , prefix , trim("in_pmid          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_pint        , prefix , trim("in_pint          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_pdel        , prefix , trim("in_pdel          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_ul          , prefix , trim("in_ul            ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_input_vl          , prefix , trim("in_vl            ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_u_wind      , prefix , trim("state_u_wind     ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_v_wind      , prefix , trim("state_v_wind     ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_w_wind      , prefix , trim("state_w_wind     ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_temperature , prefix , trim("state_temperature") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_qt          , prefix , trim("state_qt         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_qp          , prefix , trim("state_qp         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_state_qn          , prefix , trim("state_qn         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_qrad          , prefix , trim("rad_qrad         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_temperature   , prefix , trim("rad_temperature  ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_qv            , prefix , trim("rad_qv           ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_qc            , prefix , trim("rad_qc           ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_qi            , prefix , trim("rad_qi           ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( read_crm_rad_cld           , prefix , trim("rad_cld          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%ps               , prefix , trim("in_ps            ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%phis             , prefix , trim("in_phis          ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%ocnfrac          , prefix , trim("in_ocnfrac       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%tau00            , prefix , trim("in_tau00         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%wndls            , prefix , trim("in_wndls         ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%bflxls           , prefix , trim("in_bflxls        ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%fluxu00          , prefix , trim("in_fluxu00       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%fluxv00          , prefix , trim("in_fluxv00       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%fluxt00          , prefix , trim("in_fluxt00       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_input%fluxq00          , prefix , trim("in_fluxq00       ") , 1 , ncrms , .false. , .false. )
  call dmdf_read( crm_output%timing_factor   , prefix , trim("out_timing_factor") , 1 , ncrms , .false. , .true.  )

  do icrm = 1 , ncrms
    crm_input%zmid       (icrm,:)     = read_crm_input_zmid       (:    ,icrm)                       
    crm_input%zint       (icrm,:)     = read_crm_input_zint       (:    ,icrm)                       
    crm_input%tl         (icrm,:)     = read_crm_input_tl         (:    ,icrm)                       
    crm_input%ql         (icrm,:)     = read_crm_input_ql         (:    ,icrm)                       
    crm_input%qccl       (icrm,:)     = read_crm_input_qccl       (:    ,icrm)                       
    crm_input%qiil       (icrm,:)     = read_crm_input_qiil       (:    ,icrm)                       
    crm_input%pmid       (icrm,:)     = read_crm_input_pmid       (:    ,icrm)                       
    crm_input%pint       (icrm,:)     = read_crm_input_pint       (:    ,icrm)                       
    crm_input%pdel       (icrm,:)     = read_crm_input_pdel       (:    ,icrm)                       
    crm_input%ul         (icrm,:)     = read_crm_input_ul         (:    ,icrm)                       
    crm_input%vl         (icrm,:)     = read_crm_input_vl         (:    ,icrm)                       
    crm_state%u_wind     (icrm,:,:,:) = read_crm_state_u_wind     (:,:,:,icrm) 
    crm_state%v_wind     (icrm,:,:,:) = read_crm_state_v_wind     (:,:,:,icrm) 
    crm_state%w_wind     (icrm,:,:,:) = read_crm_state_w_wind     (:,:,:,icrm) 
    crm_state%temperature(icrm,:,:,:) = read_crm_state_temperature(:,:,:,icrm) 
    crm_state%qt         (icrm,:,:,:) = read_crm_state_qt         (:,:,:,icrm) 
    crm_state%qp         (icrm,:,:,:) = read_crm_state_qp         (:,:,:,icrm) 
    crm_state%qn         (icrm,:,:,:) = read_crm_state_qn         (:,:,:,icrm) 
    crm_rad%qrad         (icrm,:,:,:) = read_crm_rad_qrad         (:,:,:,icrm) 
    crm_rad%temperature  (icrm,:,:,:) = read_crm_rad_temperature  (:,:,:,icrm) 
    crm_rad%qv           (icrm,:,:,:) = read_crm_rad_qv           (:,:,:,icrm) 
    crm_rad%qc           (icrm,:,:,:) = read_crm_rad_qc           (:,:,:,icrm) 
    crm_rad%qi           (icrm,:,:,:) = read_crm_rad_qi           (:,:,:,icrm) 
    crm_rad%cld          (icrm,:,:,:) = read_crm_rad_cld          (:,:,:,icrm) 
  enddo

  write(*,*) 'dt_gl                   : ', sum(dt_gl                   )/product(shape(dt_gl                   ))
  write(*,*) 'lat0                    : ', sum(lat0                    )/product(shape(lat0                    ))
  write(*,*) 'long0                   : ', sum(long0                   )/product(shape(long0                   ))
  write(*,*) 'crm_input%zmid          : ', sum(crm_input%zmid          )/product(shape(crm_input%zmid          ))
  write(*,*) 'crm_input%zint          : ', sum(crm_input%zint          )/product(shape(crm_input%zint          ))
  write(*,*) 'crm_input%tl            : ', sum(crm_input%tl            )/product(shape(crm_input%tl            ))
  write(*,*) 'crm_input%ql            : ', sum(crm_input%ql            )/product(shape(crm_input%ql            ))
  write(*,*) 'crm_input%qccl          : ', sum(crm_input%qccl          )/product(shape(crm_input%qccl          ))
  write(*,*) 'crm_input%qiil          : ', sum(crm_input%qiil          )/product(shape(crm_input%qiil          ))
  write(*,*) 'crm_input%ps            : ', sum(crm_input%ps            )/product(shape(crm_input%ps            ))
  write(*,*) 'crm_input%pmid          : ', sum(crm_input%pmid          )/product(shape(crm_input%pmid          ))
  write(*,*) 'crm_input%pint          : ', sum(crm_input%pint          )/product(shape(crm_input%pint          ))
  write(*,*) 'crm_input%pdel          : ', sum(crm_input%pdel          )/product(shape(crm_input%pdel          ))
  write(*,*) 'crm_input%phis          : ', sum(crm_input%phis          )/product(shape(crm_input%phis          ))
  write(*,*) 'crm_input%ul            : ', sum(crm_input%ul            )/product(shape(crm_input%ul            ))
  write(*,*) 'crm_input%vl            : ', sum(crm_input%vl            )/product(shape(crm_input%vl            ))
  write(*,*) 'crm_input%ocnfrac       : ', sum(crm_input%ocnfrac       )/product(shape(crm_input%ocnfrac       ))
  write(*,*) 'crm_input%tau00         : ', sum(crm_input%tau00         )/product(shape(crm_input%tau00         ))
  write(*,*) 'crm_input%wndls         : ', sum(crm_input%wndls         )/product(shape(crm_input%wndls         ))
  write(*,*) 'crm_input%bflxls        : ', sum(crm_input%bflxls        )/product(shape(crm_input%bflxls        ))
  write(*,*) 'crm_input%fluxu00       : ', sum(crm_input%fluxu00       )/product(shape(crm_input%fluxu00       ))
  write(*,*) 'crm_input%fluxv00       : ', sum(crm_input%fluxv00       )/product(shape(crm_input%fluxv00       ))
  write(*,*) 'crm_input%fluxt00       : ', sum(crm_input%fluxt00       )/product(shape(crm_input%fluxt00       ))
  write(*,*) 'crm_input%fluxq00       : ', sum(crm_input%fluxq00       )/product(shape(crm_input%fluxq00       ))
  write(*,*) 'crm_state%u_wind        : ', sum(crm_state%u_wind        )/product(shape(crm_state%u_wind        ))
  write(*,*) 'crm_state%v_wind        : ', sum(crm_state%v_wind        )/product(shape(crm_state%v_wind        ))
  write(*,*) 'crm_state%w_wind        : ', sum(crm_state%w_wind        )/product(shape(crm_state%w_wind        ))
  write(*,*) 'crm_state%temperature   : ', sum(crm_state%temperature   )/product(shape(crm_state%temperature   ))
  write(*,*) 'crm_state%qt            : ', sum(crm_state%qt            )/product(shape(crm_state%qt            ))
  write(*,*) 'crm_state%qp            : ', sum(crm_state%qp            )/product(shape(crm_state%qp            ))
  write(*,*) 'crm_state%qn            : ', sum(crm_state%qn            )/product(shape(crm_state%qn            ))
  write(*,*) 'crm_output%timing_factor: ', sum(crm_output%timing_factor)/product(shape(crm_output%timing_factor))
  write(*,*) 'crm_rad%qrad            : ', sum(crm_rad%qrad            )/product(shape(crm_rad%qrad            ))
  write(*,*) 'crm_rad%temperature     : ', sum(crm_rad%temperature     )/product(shape(crm_rad%temperature     ))
  write(*,*) 'crm_rad%qv              : ', sum(crm_rad%qv              )/product(shape(crm_rad%qv              ))
  write(*,*) 'crm_rad%qc              : ', sum(crm_rad%qc              )/product(shape(crm_rad%qc              ))
  write(*,*) 'crm_rad%qi              : ', sum(crm_rad%qi              )/product(shape(crm_rad%qi              ))
  write(*,*) 'crm_rad%cld             : ', sum(crm_rad%cld             )/product(shape(crm_rad%cld             ))
  write(*,*) 'Running the CRM'

  ! Run the code
  call crm( ncrms, dt_gl(1), plev, crm_input, crm_state, crm_rad, crm_output, lat0, long0 )

  write(*,*) 'Finished Running the CRM'
  write(*,*) 
  write(*,*) 'crm_state%u_wind        : ', sum(crm_state%u_wind        ) /product(shape(crm_state%u_wind        ))
  write(*,*) 'crm_state%v_wind        : ', sum(crm_state%v_wind        ) /product(shape(crm_state%v_wind        ))
  write(*,*) 'crm_state%w_wind        : ', sum(crm_state%w_wind        ) /product(shape(crm_state%w_wind        ))
  write(*,*) 'crm_state%temperature   : ', sum(crm_state%temperature   ) /product(shape(crm_state%temperature   ))
  write(*,*) 'crm_state%qt            : ', sum(crm_state%qt            ) /product(shape(crm_state%qt            ))
  write(*,*) 'crm_state%qp            : ', sum(crm_state%qp            ) /product(shape(crm_state%qp            ))
  write(*,*) 'crm_state%qn            : ', sum(crm_state%qn            ) /product(shape(crm_state%qn            ))
  write(*,*) 'crm_output%qcl          : ', sum(crm_output%qcl          ) /product(shape(crm_output%qcl          ))
  write(*,*) 'crm_output%qci          : ', sum(crm_output%qci          ) /product(shape(crm_output%qci          ))
  write(*,*) 'crm_output%qpl          : ', sum(crm_output%qpl          ) /product(shape(crm_output%qpl          ))
  write(*,*) 'crm_output%qpi          : ', sum(crm_output%qpi          ) /product(shape(crm_output%qpi          ))
  write(*,*) 'crm_output%tk           : ', sum(crm_output%tk           ) /product(shape(crm_output%tk           ))
  write(*,*) 'crm_output%tkh          : ', sum(crm_output%tkh          ) /product(shape(crm_output%tkh          ))
  write(*,*) 'crm_output%prec_crm     : ', sum(crm_output%prec_crm     ) /product(shape(crm_output%prec_crm     ))
  write(*,*) 'crm_output%cltot        : ', sum(crm_output%cltot        ) /product(shape(crm_output%cltot        ))
  write(*,*) 'crm_output%clhgh        : ', sum(crm_output%clhgh        ) /product(shape(crm_output%clhgh        ))
  write(*,*) 'crm_output%clmed        : ', sum(crm_output%clmed        ) /product(shape(crm_output%clmed        ))
  write(*,*) 'crm_output%cllow        : ', sum(crm_output%cllow        ) /product(shape(crm_output%cllow        ))
  write(*,*) 'crm_output%cldtop       : ', sum(crm_output%cldtop       ) /product(shape(crm_output%cldtop       ))
  write(*,*) 'crm_output%precc        : ', sum(crm_output%precc        ) /product(shape(crm_output%precc        ))
  write(*,*) 'crm_output%precl        : ', sum(crm_output%precl        ) /product(shape(crm_output%precl        ))
  write(*,*) 'crm_output%precsc       : ', sum(crm_output%precsc       ) /product(shape(crm_output%precsc       ))
  write(*,*) 'crm_output%precsl       : ', sum(crm_output%precsl       ) /product(shape(crm_output%precsl       ))
  write(*,*) 'crm_output%qc_mean      : ', sum(crm_output%qc_mean      ) /product(shape(crm_output%qc_mean      ))
  write(*,*) 'crm_output%qi_mean      : ', sum(crm_output%qi_mean      ) /product(shape(crm_output%qi_mean      ))
  write(*,*) 'crm_output%qs_mean      : ', sum(crm_output%qs_mean      ) /product(shape(crm_output%qs_mean      ))
  write(*,*) 'crm_output%qg_mean      : ', sum(crm_output%qg_mean      ) /product(shape(crm_output%qg_mean      ))
  write(*,*) 'crm_output%qr_mean      : ', sum(crm_output%qr_mean      ) /product(shape(crm_output%qr_mean      ))
  write(*,*) 'crm_output%sltend       : ', sum(crm_output%sltend       ) /product(shape(crm_output%sltend       ))
  write(*,*) 'crm_output%qltend       : ', sum(crm_output%qltend       ) /product(shape(crm_output%qltend       ))
  write(*,*) 'crm_output%qcltend      : ', sum(crm_output%qcltend      ) /product(shape(crm_output%qcltend      ))
  write(*,*) 'crm_output%qiltend      : ', sum(crm_output%qiltend      ) /product(shape(crm_output%qiltend      ))
  write(*,*) 'crm_output%cld          : ', sum(crm_output%cld          ) /product(shape(crm_output%cld          ))
  write(*,*) 'crm_output%gicewp       : ', sum(crm_output%gicewp       ) /product(shape(crm_output%gicewp       ))
  write(*,*) 'crm_output%gliqwp       : ', sum(crm_output%gliqwp       ) /product(shape(crm_output%gliqwp       ))
  write(*,*) 'crm_output%mctot        : ', sum(crm_output%mctot        ) /product(shape(crm_output%mctot        ))
  write(*,*) 'crm_output%mcup         : ', sum(crm_output%mcup         ) /product(shape(crm_output%mcup         ))
  write(*,*) 'crm_output%mcdn         : ', sum(crm_output%mcdn         ) /product(shape(crm_output%mcdn         ))
  write(*,*) 'crm_output%mcuup        : ', sum(crm_output%mcuup        ) /product(shape(crm_output%mcuup        ))
  write(*,*) 'crm_output%mcudn        : ', sum(crm_output%mcudn        ) /product(shape(crm_output%mcudn        ))
  write(*,*) 'crm_output%mu_crm       : ', sum(crm_output%mu_crm       ) /product(shape(crm_output%mu_crm       ))
  write(*,*) 'crm_output%md_crm       : ', sum(crm_output%md_crm       ) /product(shape(crm_output%md_crm       ))
  write(*,*) 'crm_output%du_crm       : ', sum(crm_output%du_crm       ) /product(shape(crm_output%du_crm       ))
  write(*,*) 'crm_output%eu_crm       : ', sum(crm_output%eu_crm       ) /product(shape(crm_output%eu_crm       ))
  write(*,*) 'crm_output%ed_crm       : ', sum(crm_output%ed_crm       ) /product(shape(crm_output%ed_crm       ))
  write(*,*) 'crm_output%jt_crm       : ', sum(crm_output%jt_crm       ) /product(shape(crm_output%jt_crm       ))
  write(*,*) 'crm_output%mx_crm       : ', sum(crm_output%mx_crm       ) /product(shape(crm_output%mx_crm       ))
  write(*,*) 'crm_output%flux_qt      : ', sum(crm_output%flux_qt      ) /product(shape(crm_output%flux_qt      ))
  write(*,*) 'crm_output%fluxsgs_qt   : ', sum(crm_output%fluxsgs_qt   ) /product(shape(crm_output%fluxsgs_qt   ))
  write(*,*) 'crm_output%tkez         : ', sum(crm_output%tkez         ) /product(shape(crm_output%tkez         ))
  write(*,*) 'crm_output%tkesgsz      : ', sum(crm_output%tkesgsz      ) /product(shape(crm_output%tkesgsz      ))
  write(*,*) 'crm_output%tkz          : ', sum(crm_output%tkz          ) /product(shape(crm_output%tkz          ))
  write(*,*) 'crm_output%flux_u       : ', sum(crm_output%flux_u       ) /product(shape(crm_output%flux_u       ))
  write(*,*) 'crm_output%flux_v       : ', sum(crm_output%flux_v       ) /product(shape(crm_output%flux_v       ))
  write(*,*) 'crm_output%flux_qp      : ', sum(crm_output%flux_qp      ) /product(shape(crm_output%flux_qp      ))
  write(*,*) 'crm_output%precflux     : ', sum(crm_output%precflux     ) /product(shape(crm_output%precflux     ))
  write(*,*) 'crm_output%qt_ls        : ', sum(crm_output%qt_ls        ) /product(shape(crm_output%qt_ls        ))
  write(*,*) 'crm_output%qt_trans     : ', sum(crm_output%qt_trans     ) /product(shape(crm_output%qt_trans     ))
  write(*,*) 'crm_output%qp_trans     : ', sum(crm_output%qp_trans     ) /product(shape(crm_output%qp_trans     ))
  write(*,*) 'crm_output%qp_fall      : ', sum(crm_output%qp_fall      ) /product(shape(crm_output%qp_fall      ))
  write(*,*) 'crm_output%qp_src       : ', sum(crm_output%qp_src       ) /product(shape(crm_output%qp_src       ))
  write(*,*) 'crm_output%qp_evp       : ', sum(crm_output%qp_evp       ) /product(shape(crm_output%qp_evp       ))
  write(*,*) 'crm_output%t_ls         : ', sum(crm_output%t_ls         ) /product(shape(crm_output%t_ls         ))
  write(*,*) 'crm_output%prectend     : ', sum(crm_output%prectend     ) /product(shape(crm_output%prectend     ))
  write(*,*) 'crm_output%precstend    : ', sum(crm_output%precstend    ) /product(shape(crm_output%precstend    ))
  write(*,*) 'crm_output%taux         : ', sum(crm_output%taux         ) /product(shape(crm_output%taux         ))
  write(*,*) 'crm_output%tauy         : ', sum(crm_output%tauy         ) /product(shape(crm_output%tauy         ))
  write(*,*) 'crm_output%z0m          : ', sum(crm_output%z0m          ) /product(shape(crm_output%z0m          ))
  write(*,*) 'crm_output%timing_factor: ', sum(crm_output%timing_factor) /product(shape(crm_output%timing_factor))



contains



end program driver


