#ifndef _HAMILTONIAN_H_
#define _HAMILTONIAN_H_

#include "common.h"
#include "kinetic_energy.h"
#include "layer_models.h"
#include "compressible_euler.h"
#include "anelastic.h"
#include "functionals.h"



//HERE I THINK WE ACTUALLY DEFINE FULL HAMILTONIANS?
//ISSUE- HOW DO WE HANDLE INITIALIZATION/CONSTANTS IF MULTIPLE H WANT THEM?
//REALLY ONLY "STATIC ENERGY" PART NEEDS THEM FOR NOW
//ALTHOUGH THIS WILL CHANGE WITH COVARIANT VELOCITY IN TERRAIN-FOLLOWING COORDS IE GRAD Z/GRAD GEOP IS NEEDED....


#endif
