#ifndef _HAMILTONIAN_ANELASTIC_H_
#define _HAMILTONIAN_ANELASTIC_H_

#include "common.h"
#include "thermo.h"


// AN/MAN variants
// HOW DO WE TREAT DHDX, ETC. HERE SINCE WE HAVE A NEW ARGUMENT: P^PRIME?
// P^PRIME SOLVE IS NEEDED FOR DHDX in Hs and also for computing IE in Hs
// SHOULD THESE DETERMINE LHS AND RHS OF P EQN? YES, IT IS A CONSTRAINT BASED EQN THAT DEPENDS ON THERMO AND VARIABLES....
// MAYBE PPRIME LIVES IN DHDX LIKE HS/GEOP PROPERLY SHOULD?
// YES ACTUALLY, THIS MAKES THE MOST SENSE... 
class Functional_PVPE_AN {};
class Hamiltonian_Hk_AN {};
class Hamiltonian_AN_Hs {};
class Hamiltonian_MAN_Hs {};


#endif